var namespacedepicture__menu_1_1presentations_1_1view__models_1_1operations_1_1detail__operation__menu =
[
    [ "menu_operator_impl", "structdepicture__menu_1_1presentations_1_1view__models_1_1operations_1_1detail__operation__menu_1_1menu__operator__impl.html", "structdepicture__menu_1_1presentations_1_1view__models_1_1operations_1_1detail__operation__menu_1_1menu__operator__impl" ],
    [ "menu_create_operator_impl", "structdepicture__menu_1_1presentations_1_1view__models_1_1operations_1_1detail__operation__menu_1_1menu__create__operator__impl.html", "structdepicture__menu_1_1presentations_1_1view__models_1_1operations_1_1detail__operation__menu_1_1menu__create__operator__impl" ],
    [ "menu_erase_operator_impl", "structdepicture__menu_1_1presentations_1_1view__models_1_1operations_1_1detail__operation__menu_1_1menu__erase__operator__impl.html", "structdepicture__menu_1_1presentations_1_1view__models_1_1operations_1_1detail__operation__menu_1_1menu__erase__operator__impl" ]
];