var namespacedepicture__menu_1_1usecase_1_1dto =
[
    [ "action_created", "structdepicture__menu_1_1usecase_1_1dto_1_1action__created.html", "structdepicture__menu_1_1usecase_1_1dto_1_1action__created" ],
    [ "basic_action_config_update", "structdepicture__menu_1_1usecase_1_1dto_1_1basic__action__config__update.html", "structdepicture__menu_1_1usecase_1_1dto_1_1basic__action__config__update" ],
    [ "command_created", "structdepicture__menu_1_1usecase_1_1dto_1_1command__created.html", "structdepicture__menu_1_1usecase_1_1dto_1_1command__created" ],
    [ "common_action_select", "structdepicture__menu_1_1usecase_1_1dto_1_1common__action__select.html", "structdepicture__menu_1_1usecase_1_1dto_1_1common__action__select" ],
    [ "common_action_select_changed", "structdepicture__menu_1_1usecase_1_1dto_1_1common__action__select__changed.html", "structdepicture__menu_1_1usecase_1_1dto_1_1common__action__select__changed" ],
    [ "config_view_created", "structdepicture__menu_1_1usecase_1_1dto_1_1config__view__created.html", "structdepicture__menu_1_1usecase_1_1dto_1_1config__view__created" ],
    [ "view_changed_notify", "structdepicture__menu_1_1usecase_1_1dto_1_1view__changed__notify.html", "structdepicture__menu_1_1usecase_1_1dto_1_1view__changed__notify" ],
    [ "view_changed_notify_with_kind", "structdepicture__menu_1_1usecase_1_1dto_1_1view__changed__notify__with__kind.html", "structdepicture__menu_1_1usecase_1_1dto_1_1view__changed__notify__with__kind" ],
    [ "view_changed_notify_with_kind_event", "structdepicture__menu_1_1usecase_1_1dto_1_1view__changed__notify__with__kind__event.html", "structdepicture__menu_1_1usecase_1_1dto_1_1view__changed__notify__with__kind__event" ],
    [ "trigger_activate", "structdepicture__menu_1_1usecase_1_1dto_1_1trigger__activate.html", "structdepicture__menu_1_1usecase_1_1dto_1_1trigger__activate" ],
    [ "trigger_inactivate", "structdepicture__menu_1_1usecase_1_1dto_1_1trigger__inactivate.html", "structdepicture__menu_1_1usecase_1_1dto_1_1trigger__inactivate" ],
    [ "regist_global_hotkey_trigger", "structdepicture__menu_1_1usecase_1_1dto_1_1regist__global__hotkey__trigger.html", "structdepicture__menu_1_1usecase_1_1dto_1_1regist__global__hotkey__trigger" ],
    [ "unregist_global_hotkey_trigger", "structdepicture__menu_1_1usecase_1_1dto_1_1unregist__global__hotkey__trigger.html", "structdepicture__menu_1_1usecase_1_1dto_1_1unregist__global__hotkey__trigger" ],
    [ "menu_config_update", "structdepicture__menu_1_1usecase_1_1dto_1_1menu__config__update.html", "structdepicture__menu_1_1usecase_1_1dto_1_1menu__config__update" ],
    [ "menu_created", "structdepicture__menu_1_1usecase_1_1dto_1_1menu__created.html", "structdepicture__menu_1_1usecase_1_1dto_1_1menu__created" ],
    [ "menu_item_created", "structdepicture__menu_1_1usecase_1_1dto_1_1menu__item__created.html", "structdepicture__menu_1_1usecase_1_1dto_1_1menu__item__created" ],
    [ "menu_item_duplicate", "structdepicture__menu_1_1usecase_1_1dto_1_1menu__item__duplicate.html", "structdepicture__menu_1_1usecase_1_1dto_1_1menu__item__duplicate" ],
    [ "menu_item_order_change", "structdepicture__menu_1_1usecase_1_1dto_1_1menu__item__order__change.html", "structdepicture__menu_1_1usecase_1_1dto_1_1menu__item__order__change" ],
    [ "menu_update", "structdepicture__menu_1_1usecase_1_1dto_1_1menu__update.html", "structdepicture__menu_1_1usecase_1_1dto_1_1menu__update" ],
    [ "menu_updated", "structdepicture__menu_1_1usecase_1_1dto_1_1menu__updated.html", "structdepicture__menu_1_1usecase_1_1dto_1_1menu__updated" ],
    [ "trigger_created", "structdepicture__menu_1_1usecase_1_1dto_1_1trigger__created.html", "structdepicture__menu_1_1usecase_1_1dto_1_1trigger__created" ],
    [ "action_changed_notify", "namespacedepicture__menu_1_1usecase_1_1dto.html#a9073a2c3d8d98bd2271898ee876c7fee", null ],
    [ "basic_action_configs_t", "namespacedepicture__menu_1_1usecase_1_1dto.html#a3ac07a45392827874efd43801b85ca2f", null ],
    [ "command_changed_notify", "namespacedepicture__menu_1_1usecase_1_1dto.html#a514ab62cb0fe259fdb9810eb40ce18af", null ],
    [ "menu_changed_notify", "namespacedepicture__menu_1_1usecase_1_1dto.html#ac2aaed68a427137178bb5a0a838ba75e", null ],
    [ "trigger_changed_notify", "namespacedepicture__menu_1_1usecase_1_1dto.html#a5d64ad1a61eb3ad2512237a453caea14", null ]
];