var namespacedepicture__menu_1_1applications_1_1usecase__dispatch =
[
    [ "view_presenters_stack", "classdepicture__menu_1_1applications_1_1usecase__dispatch_1_1view__presenters__stack.html", "classdepicture__menu_1_1applications_1_1usecase__dispatch_1_1view__presenters__stack" ],
    [ "config_view_dispatch", "classdepicture__menu_1_1applications_1_1usecase__dispatch_1_1config__view__dispatch.html", "classdepicture__menu_1_1applications_1_1usecase__dispatch_1_1config__view__dispatch" ]
];