var namespacedepicture__menu_1_1usecase_1_1dto =
[
    [ "action_created", "structdepicture__menu_1_1usecase_1_1dto_1_1action__created.html", "structdepicture__menu_1_1usecase_1_1dto_1_1action__created" ],
    [ "basic_action_config_update", "structdepicture__menu_1_1usecase_1_1dto_1_1basic__action__config__update.html", "structdepicture__menu_1_1usecase_1_1dto_1_1basic__action__config__update" ],
    [ "command_created", "structdepicture__menu_1_1usecase_1_1dto_1_1command__created.html", "structdepicture__menu_1_1usecase_1_1dto_1_1command__created" ],
    [ "command_updated", "structdepicture__menu_1_1usecase_1_1dto_1_1command__updated.html", "structdepicture__menu_1_1usecase_1_1dto_1_1command__updated" ],
    [ "common_action_select", "structdepicture__menu_1_1usecase_1_1dto_1_1common__action__select.html", "structdepicture__menu_1_1usecase_1_1dto_1_1common__action__select" ],
    [ "common_action_select_changed", "structdepicture__menu_1_1usecase_1_1dto_1_1common__action__select__changed.html", "structdepicture__menu_1_1usecase_1_1dto_1_1common__action__select__changed" ],
    [ "nop_command_parameter", "structdepicture__menu_1_1usecase_1_1dto_1_1nop__command__parameter.html", "structdepicture__menu_1_1usecase_1_1dto_1_1nop__command__parameter" ],
    [ "shellexecute_command_parameter", "structdepicture__menu_1_1usecase_1_1dto_1_1shellexecute__command__parameter.html", "structdepicture__menu_1_1usecase_1_1dto_1_1shellexecute__command__parameter" ],
    [ "open_sub_menu_command_parameter", "structdepicture__menu_1_1usecase_1_1dto_1_1open__sub__menu__command__parameter.html", "structdepicture__menu_1_1usecase_1_1dto_1_1open__sub__menu__command__parameter" ],
    [ "config_view_created", "structdepicture__menu_1_1usecase_1_1dto_1_1config__view__created.html", "structdepicture__menu_1_1usecase_1_1dto_1_1config__view__created" ],
    [ "view_changed_notify", "structdepicture__menu_1_1usecase_1_1dto_1_1view__changed__notify.html", "structdepicture__menu_1_1usecase_1_1dto_1_1view__changed__notify" ],
    [ "view_changed_notify_with_kind", "structdepicture__menu_1_1usecase_1_1dto_1_1view__changed__notify__with__kind.html", "structdepicture__menu_1_1usecase_1_1dto_1_1view__changed__notify__with__kind" ],
    [ "view_changed_notify_with_kind_event", "structdepicture__menu_1_1usecase_1_1dto_1_1view__changed__notify__with__kind__event.html", "structdepicture__menu_1_1usecase_1_1dto_1_1view__changed__notify__with__kind__event" ],
    [ "trigger_activate", "structdepicture__menu_1_1usecase_1_1dto_1_1trigger__activate.html", "structdepicture__menu_1_1usecase_1_1dto_1_1trigger__activate" ],
    [ "trigger_inactivate", "structdepicture__menu_1_1usecase_1_1dto_1_1trigger__inactivate.html", "structdepicture__menu_1_1usecase_1_1dto_1_1trigger__inactivate" ],
    [ "regist_global_hotkey_trigger", "structdepicture__menu_1_1usecase_1_1dto_1_1regist__global__hotkey__trigger.html", "structdepicture__menu_1_1usecase_1_1dto_1_1regist__global__hotkey__trigger" ],
    [ "unregist_global_hotkey_trigger", "structdepicture__menu_1_1usecase_1_1dto_1_1unregist__global__hotkey__trigger.html", "structdepicture__menu_1_1usecase_1_1dto_1_1unregist__global__hotkey__trigger" ],
    [ "menu_config_update", "structdepicture__menu_1_1usecase_1_1dto_1_1menu__config__update.html", "structdepicture__menu_1_1usecase_1_1dto_1_1menu__config__update" ],
    [ "menu_created", "structdepicture__menu_1_1usecase_1_1dto_1_1menu__created.html", "structdepicture__menu_1_1usecase_1_1dto_1_1menu__created" ],
    [ "menu_item_created", "structdepicture__menu_1_1usecase_1_1dto_1_1menu__item__created.html", "structdepicture__menu_1_1usecase_1_1dto_1_1menu__item__created" ],
    [ "menu_item_duplicate", "structdepicture__menu_1_1usecase_1_1dto_1_1menu__item__duplicate.html", "structdepicture__menu_1_1usecase_1_1dto_1_1menu__item__duplicate" ],
    [ "menu_item_order_change", "structdepicture__menu_1_1usecase_1_1dto_1_1menu__item__order__change.html", "structdepicture__menu_1_1usecase_1_1dto_1_1menu__item__order__change" ],
    [ "menu_item_update", "structdepicture__menu_1_1usecase_1_1dto_1_1menu__item__update.html", "structdepicture__menu_1_1usecase_1_1dto_1_1menu__item__update" ],
    [ "menu_item_updated", "structdepicture__menu_1_1usecase_1_1dto_1_1menu__item__updated.html", "structdepicture__menu_1_1usecase_1_1dto_1_1menu__item__updated" ],
    [ "menu_update", "structdepicture__menu_1_1usecase_1_1dto_1_1menu__update.html", "structdepicture__menu_1_1usecase_1_1dto_1_1menu__update" ],
    [ "menu_updated", "structdepicture__menu_1_1usecase_1_1dto_1_1menu__updated.html", "structdepicture__menu_1_1usecase_1_1dto_1_1menu__updated" ],
    [ "shellexecute_command_update", "structdepicture__menu_1_1usecase_1_1dto_1_1shellexecute__command__update.html", "structdepicture__menu_1_1usecase_1_1dto_1_1shellexecute__command__update" ],
    [ "trigger_created", "structdepicture__menu_1_1usecase_1_1dto_1_1trigger__created.html", "structdepicture__menu_1_1usecase_1_1dto_1_1trigger__created" ],
    [ "action_changed_notify", "namespacedepicture__menu_1_1usecase_1_1dto.html#a4dfbd228890f0def8acaf7d45c94bc3a", null ],
    [ "basic_action_configs_t", "namespacedepicture__menu_1_1usecase_1_1dto.html#a3ac07a45392827874efd43801b85ca2f", null ],
    [ "command_changed_notify", "namespacedepicture__menu_1_1usecase_1_1dto.html#a534f6b3e9b748ce256f83727c8e0155f", null ],
    [ "common_command_parameter", "namespacedepicture__menu_1_1usecase_1_1dto.html#a2e634448b235859431a2a8a8c595f49d", null ],
    [ "menu_changed_notify", "namespacedepicture__menu_1_1usecase_1_1dto.html#aef2883be1f18cb2f90e3e02fb2053bfe", null ],
    [ "trigger_changed_notify", "namespacedepicture__menu_1_1usecase_1_1dto.html#a37b47b98cf0fae3f1e66fd4996e285f7", null ]
];