var namespacedepicture__menu =
[
    [ "util", "namespacedepicture__menu_1_1util.html", "namespacedepicture__menu_1_1util" ],
    [ "reflection", "namespacedepicture__menu_1_1reflection.html", "namespacedepicture__menu_1_1reflection" ],
    [ "detail", "namespacedepicture__menu_1_1detail.html", "namespacedepicture__menu_1_1detail" ],
    [ "type_traits", "namespacedepicture__menu_1_1type__traits.html", "namespacedepicture__menu_1_1type__traits" ],
    [ "win32", "namespacedepicture__menu_1_1win32.html", "namespacedepicture__menu_1_1win32" ],
    [ "applications", "namespacedepicture__menu_1_1applications.html", "namespacedepicture__menu_1_1applications" ],
    [ "cs_binding", "namespacedepicture__menu_1_1cs__binding.html", "namespacedepicture__menu_1_1cs__binding" ],
    [ "detail_d_menu", "namespacedepicture__menu_1_1detail__d__menu.html", "namespacedepicture__menu_1_1detail__d__menu" ],
    [ "application", "namespacedepicture__menu_1_1application.html", "namespacedepicture__menu_1_1application" ],
    [ "controls", "namespacedepicture__menu_1_1controls.html", "namespacedepicture__menu_1_1controls" ],
    [ "domain", "namespacedepicture__menu_1_1domain.html", "namespacedepicture__menu_1_1domain" ],
    [ "concepts", "namespacedepicture__menu_1_1concepts.html", "namespacedepicture__menu_1_1concepts" ],
    [ "presentations", "namespacedepicture__menu_1_1presentations.html", "namespacedepicture__menu_1_1presentations" ],
    [ "presentation", "namespacedepicture__menu_1_1presentation.html", "namespacedepicture__menu_1_1presentation" ],
    [ "repositories", "namespacedepicture__menu_1_1repositories.html", "namespacedepicture__menu_1_1repositories" ],
    [ "repository", "namespacedepicture__menu_1_1repository.html", "namespacedepicture__menu_1_1repository" ],
    [ "ranges", "namespacedepicture__menu_1_1ranges.html", "namespacedepicture__menu_1_1ranges" ],
    [ "usecase", "namespacedepicture__menu_1_1usecase.html", "namespacedepicture__menu_1_1usecase" ],
    [ "conv_mapping", "namespacedepicture__menu_1_1conv__mapping.html", "namespacedepicture__menu_1_1conv__mapping" ],
    [ "test", "namespacedepicture__menu_1_1test.html", "namespacedepicture__menu_1_1test" ],
    [ "singleton", "classdepicture__menu_1_1singleton.html", "classdepicture__menu_1_1singleton" ],
    [ "debug_interface_impl", "structdepicture__menu_1_1debug__interface__impl.html", "structdepicture__menu_1_1debug__interface__impl" ],
    [ "hotkey_event_source", "classdepicture__menu_1_1hotkey__event__source.html", "classdepicture__menu_1_1hotkey__event__source" ],
    [ "hotkey_manager", "classdepicture__menu_1_1hotkey__manager.html", "classdepicture__menu_1_1hotkey__manager" ],
    [ "app_transacion_t", "namespacedepicture__menu.html#a3f5fb0c9223d976f61f05d356ca2908b", null ],
    [ "application_config_repository_accesser", "namespacedepicture__menu.html#a907635a0c21b9ddbdeebeacc559a60c6", null ],
    [ "application_info_archiver", "namespacedepicture__menu.html#ae23267df62ee85b256529689c929665f", null ],
    [ "application_option_repository_accesser", "namespacedepicture__menu.html#a2e7947483668318c86e19a21940ea7f9", null ],
    [ "constexpr_string", "namespacedepicture__menu.html#a6c1ee86b4e22d373f58ab39a5349ddc9", null ],
    [ "constexpr_wstring", "namespacedepicture__menu.html#a9cee412d19c52d3cd58e52a31e7ec4c2", null ],
    [ "core_interface", "namespacedepicture__menu.html#a92e463b70c341aa89e513e9a70727361", null ],
    [ "debug_interface", "namespacedepicture__menu.html#adbafaed25f7b9f6ee4567df6f78cd5cb", null ],
    [ "singleton< T >::init_flag_", "namespacedepicture__menu.html#a9850a30d6c7fbdfc1f15aa729db581d9", null ],
    [ "singleton< T >::instance_", "namespacedepicture__menu.html#ab093e4809e6ccec6e70674c1ced75613", null ]
];