var namespacedepicture__menu_1_1domain_1_1commands_1_1buildin_1_1detail__commands__buildin =
[
    [ "open_menu_command_parameter_data", "structdepicture__menu_1_1domain_1_1commands_1_1buildin_1_1detail__commands__buildin_1_1open__menu__command__parameter__data.html", "structdepicture__menu_1_1domain_1_1commands_1_1buildin_1_1detail__commands__buildin_1_1open__menu__command__parameter__data" ]
];