var open__menu__command__parameter_8hpp =
[
    [ "depicture_menu::domain::commands::buildin::detail_commands_buildin::open_menu_command_parameter_data", "structdepicture__menu_1_1domain_1_1commands_1_1buildin_1_1detail__commands__buildin_1_1open__menu__command__parameter__data.html", "structdepicture__menu_1_1domain_1_1commands_1_1buildin_1_1detail__commands__buildin_1_1open__menu__command__parameter__data" ],
    [ "depicture_menu::domain::commands::buildin::open_menu_command_parameter", "classdepicture__menu_1_1domain_1_1commands_1_1buildin_1_1open__menu__command__parameter.html", "classdepicture__menu_1_1domain_1_1commands_1_1buildin_1_1open__menu__command__parameter" ]
];